### ISSUE TITLE
Build fails when previous versions use deprecated Sphinx config

### ISSUE THREAD

**Issue by sybrenjansen** [devanshshukla99/sphinx-versioned-docs#30]
I came across your repo just recently and tried to give it a shot. It seems like it's the only one to provide versioned builds that is compatible with the latest Python versions. Or are there others?

Anyway, I was having some difficulty getting this to work for a project of mine and was wondering if you could help me out.

The project I have is already a few years old and used Sphinx 3.2, which I now really need to upgrade because my old sphinx versioning code required Python 3.6, which is EOL. When using this old version back then I used `app.add_stylesheet` to add a custom css file, which has been deprecated in Sphinx 6.0.0 (also already a few years old) in favor of `app.add_css_file`. Of course I can make this change in the current branch, but when I run `sphinx-versioned`, it fails when trying to build the docs for those older releases because in those commits there is still `app.add_stylesheet`, which no longer works on the latest Sphinx.

Is there anything I can do to fix this? I can pin Sphinx < 6.0.0, but that will be a temporary solution until Python 3.10 becomes EOL. I would like to have a proper solution so I can use the latest Sphinx instead. Any help would be appreciated.

Some brain farts of mine:
- Add support for monkey-patching the `conf.py` file
- Keep track of a list of deprecated functions and their replacements and do a temporary search/replace for each checkout

**Comment by devanshshukla99** [comment]
Hi, yeahh, I suppose I can monkey patch the `add_stylesheet` method to `add_css_file` for now and later add other deprecated funcs.

**Comment by devanshshukla99** [comment]
I've added the monkey patch to the linked pr.
Could you test this once @sybrenjansen? I've tested it naively, but a more robust test will be more helpful.
