### ISSUE TITLE
No version selector menu

### ISSUE THREAD

**Issue by hakonhagland** [devanshshukla99/sphinx-versioned-docs#71]
I use the following command to build the documentation:

```
$ sphinx-versioned -b "sphinx_versioned, v1.0, v2.0" -m sphinx_versioned 
| SUCCESS  | - latched into the git repo
| SUCCESS  | - located conf.py
| INFO     | - Selecting tag for further processing: sphinx_versioned
| CRITICAL | - Branch not found: ``, use `--force` to force the build
| INFO     | - Selecting tag for further processing: v1.0
| CRITICAL | - Branch not found: ``, use `--force` to force the build
| INFO     | - Selecting tag for further processing: v2.0
| INFO     | - pre-building: sphinx_versioned
| SUCCESS  | - pre-build succeded for sphinx_versioned :)
| INFO     | - pre-building: v1.0
| SUCCESS  | - pre-build succeded for v1.0 :)
| INFO     | - pre-building: v2.0
| SUCCESS  | - pre-build succeded for v2.0 :)
| SUCCESS  | - Prebuilding successful for sphinx_versioned, v1.0, v2.0
| INFO     | - Building: sphinx_versioned
| INFO     | - Theme: sphinx_rtd_theme
| SUCCESS  | - build succeded for sphinx_versioned ;)
| INFO     | - Building: v1.0
| INFO     | - Theme: sphinx_rtd_theme
| SUCCESS  | - build succeded for v1.0 ;)
| INFO     | - Building: v2.0
| INFO     | - Theme: sphinx_rtd_theme
| SUCCESS  | - build succeded for v2.0 ;)
| SUCCESS  | - main branch: `sphinx_versioned`; generating top-level `index.html`

 Successfully built sphinx_versioned, v1.0, v2.0 
```

However, when I visit the generated `index.html` no version selection menu is shown on the front page:

![image](https://github.com/devanshshukla99/sphinx-versioned-docs/assets/6708379/41df9cbc-1ec6-4886-8af2-e1fc4d0a0e79)

**Comment by hakonhagland** [comment]
>
```
| SUCCESS  | - main branch: `sphinx_versioned`; generating top-level `index.html`
```

I am running this from branch `sphinx_versioned`. Why does it say "main branch" here?

**Comment by hakonhagland** [comment]
> when I visit the generated index.html no version selection menu is shown on the front page:

Found the problem: I visited `_build/html/index.html` which was probably a directory generated `sphinx-build` not by `sphinx-versioned`. The correct index.html is at `_build/index.html`

**Comment by devanshshukla99** [comment]
> > 
> 
> ```
> | SUCCESS  | - main branch: `sphinx_versioned`; generating top-level `index.html`
> ```
> 
> I am running this from branch `sphinx_versioned`. Why does it say "main branch" here?

Hi!

Essentially, unless a different output is set using ``--output``, the docs for branches are generated at `docs/_build/{branch name}/`.

`sphinx-versioned` also generates a top-level `index.html` at `docs/_build/index.html` for easier access to the main/latest branch.

Using the cli argument `-m` sets that particular branch as the main branch -- that means the top-level `index.html` will point to that specified branch.
