### ISSUE TITLE
[Question] Is there a way to exclude all branches and only build docs for tagged versions?

### ISSUE THREAD

**Issue by fdosani** [devanshshukla99/sphinx-versioned-docs#79]
Thanks for this project @devanshshukla99 

I'm trying to have versioned docs for my [project](https://github.com/capitalone/datacompy) and curious if there is a way to exclude **all** branches and **only** have tagged versions. From the docs it seems like maybe `--branch` would work but my understanding is it looks for the exact match not wild cards?

**Comment by devanshshukla99** [comment]
Hi!

Yes, you are correct, as of now, `--branch` only supports exact matches.

However, having the ability to accept wildcard entries seems pretty useful and relatively easy to implement.
I'll keep this open and will try to add it by this weekend.

**Comment by nidalJaafar** [comment]
Hi @devanshshukla99 thanks for the project

I have a suggestion: Could we add an option called `--tags` for making documentation only for tags, not branches? For example, `--tags *` could get all the tags in the repository, and `--tags "v1.0, v1.1"` could get specific tags. Right now, it seems like the setup grabs information from both branches and tags in the repository. What do you think?
